### PR TITLE
Function Library implementation

### PR DESCRIPTION
**Pull request by blkanaki**
Addresses the question of "Why isn't the A3 Function Library being used", as proposed in issue #135.
- Moved functions defined in `initFuncs.sqf` to `functions.hpp` using the new A3 Function Library format.
- Mission types themselves are still defined in `initFuncs.sqf` but all supporting functions have been moved to function library.
- Original file names and locations left intact to aid in future patches - decision to be revisited at a later date.
- All affected call/spawn/remoteExec have been refactored to account for new function prefix `"A3A_fnc_"`

### CODE REVIEW

**Comment by Barbolani77** [comment]
Hi!

This is just... amazing!!!! I can only say a big THANK YOU for all your work.

My only problem: as I am a shit gith user, I have some patch to publish before merging this, and that patch modifies several functions, so, how can we do it?

**Comment by blkanaki** [comment]
Thank you and you're welcome.

In regards to the modified functions, push any changes to the master branch as normal and this PR should keep track of any potential merge conflicts that arise, which I'll sort out as they come; I've corrected the two that occurred after the most recent commit.

I'm a pretty bargain basement user of Git myself, so we're essentially both stumbling in the dark here.

**Comment by SomeOneUnknown** [comment]
Really nice job!

**Comment by Barbolani77** [comment]
Hi! I am back to Antistasi coding this week so I will put my hands on this prior to anything, so I avoid conflicts. Wish me luck :)

**Comment by Barbolani77** [comment]
Ok, I think I've done it! Thanks a lot man!

**Comment by Barbolani77** [comment]
Hi!
I found something veeeery strange. The unit init (CREATE\NATOinit.sqf, called with A3A_fnc_NATOInit) is sometimes called, sometimes not. This has caused several bug reports like the revive not working, or issues with the loadout (which made me notice it).

Sometimes the function is just... not called! No error pops up.

Very very strange and I am totally lost.

This is a very core thing and I need to fix it ASAP!

**Comment by Barbolani77** [comment]
the issue seems to appear totally randomly, repeating the same steps result sometimes on the funciton in, and sometimes with the function lost.

**Comment by blkanaki** [comment]
That's an interesting one, what are the steps to reproduce? Is the issue limited to single player or does it happen in multiplayer as well?

I'm about to head out the door for work but I'll give it a look over when I get home.

**Comment by Barbolani77** [comment]
Tested in SP, but the script runs local.

To reproduce, just put a cheap hint in the script first line and teleport near a garrison.

Sometimes It spawn, sometimes not

**Comment by blkanaki** [comment]
I believe I've located the issue; the forEach loop within the conditional check for `_revelar` at the end of `NATOinit.sqf` line 231 is missing the closing parenthesis, brace and semicolon and the conditional closure itself is missing the brace and semicolon.

EOF currently consists of
```
	} forEach allUnits select {(vehicle _x isKindOf "Air") and (_x distance _unit <= distanciaSPWN
```
Whereas it should be
```
	} forEach allUnits select {(vehicle _x isKindOf "Air") and (_x distance _unit <= distanciaSPWN)};
};
```

--

I've added additional debug logging before and after every call to A3A_fnc_NATOinit, in addition to NATOinit.sqf itself. I've given it a few hours of testing and A3A_fnc_NATOinit is once again working.

**Comment by Barbolani77** [comment]
F..... GOD BLESS YOU

**Pull request merged**
