### PR TITLE
changes to mineSweep to try to avoid death while clearing APERS mines

### PR DESCRIPTION
**Pull request by wriley**
My mine sweepers kept stepping on mines in dense APERS fields left by the enemy so I tried to make it a little smarter. Note, this is only tested on Armia Krajowa version.

1. Add Mine Detector to unit
2. Go back to truck after each mine
  a. helps avoid stepping on other mines
  b. realism?

### CODE REVIEW

**Comment by Barbolani77** [comment]
Probably with 1 the problem is solved. Have you tried?

**Comment by wriley** [comment]
> Probably with 1 the problem is solved. Have you tried?

I started with the change in movement and liked the more realistic approach so kept it in. It's probably not necessary with the addition of the mine detector but will do some testing.

**Comment by Barbolani77** [comment]
because its prolly the cause of death :) In my tests I allways did it on deployed minefields and the AI eludes the mines pretty well

BTW an Idea for movement, instead of doMove, use orderGetIn true, as the vanilla FSM is simpler and more quick (and ignores walls :) )

**Comment by wriley** [comment]
The change in movement I made was because of death. The enemy put down an especially dense APERS minefield on a hill and a lot of the mines are not revealed so the AI happily kills himself by walking over the mines. Adding the mine detector seems to let him find and avoid these mines that aren't revealed. I'm doing some testing and then will update the PR. Thanks for the movement tip.

**Comment by wriley** [comment]
I reverted the moving to truck so now it just adds a mine detector and some hints/logging. With the mine detector the AI has no trouble clearing the dense APERS minefield.

**Comment by Barbolani77** [comment]
meeeerging! Thanks! I will remove all the debug messages.

**Pull request merged**
